### ISSUE TITLE
Can not reach `https://127.0.0.1:2999/liveclientdata/playerlist` without opening port in firewall

### ISSUE THREAD

**Issue by Vianpyro** [MuricanWizard/LoL_Tryhard#2]
I tried running [getRitoData.py](https://github.com/MuricanWizard/LoL_Tryhard/blob/master/getRitoData.py) but couldn't load any content because the request isn't secure.
Isn't there a way to make the request authorized/secure so I (random user) don't have to open the port in my firewall?

**Comment by akhilred36** [comment]
@Vianpyro Unfortunately, no. You will need to skip the check with whatever https requests tool you're using. Also, getRitoData.py works only with the ElectronJS app because there needs to be some information passed onto it to gather the data. Are you sure you're using it the right way?

**Comment by Vianpyro** [comment]
Ok, I was hoping for some sort of request to the user that could've been made but no problem, I'll just write things in a Readme.
And I modified your code to make it work just by itself.
Also thank you very much for answering me as fast as you did and good luck with your project!
